2025-07-13 15:51:44,574 - CRITICAL - Unexpected error: 'TodoController' object has no attribute '_run_app'
Traceback (most recent call last):
  File "D:\dev\maktab\todo_app\version_2\src\controllers\todo_controller.py", line 86, in run
    self._run_app()
    ^^^^^^^^^^^^^
AttributeError: 'TodoController' object has no attribute '_run_app'
